# Site settings
title: Blog
email: realchainlife@protonmail.com
description: " | RealChainğŸ®Ê• â€¢á´¥â€¢Ê”"
baseurl: "/blog"
url: ""
future: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 10

# Gems
gems: [jekyll-paginate]
